language: emacs-lisp
sudo: false
before_install:
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - export PATH="/home/travis/.evm/bin:$PATH"
  - evm config path /tmp
  - evm install $EVM_EMACS --use
  - cp init.example.el init.el
  - make
env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis

script:
  - make