os: osx
language: emacs-lisp
sudo: false
before_install:
  - brew update && brew bundle

install:
  - git clone https://github.com/casouri/lunarymacs.git .emacs.d --recurse-submodules
  - make install-emacs25
  - cd .emacs.d
  - cp init.example.el init.el

script:
  - make
