os: osx
language: emacs-lisp
sudo: false

install:
  - git clone https://github.com/casouri/lunarymacs.git .emacs.d --recurse-submodules
  - cd .emacs.d
  - make install-emacs25
  - cp init.example.el init.el

script:
  - make

